/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_delthas_skype_SkyLoginConnector */

#ifndef _SkyLoginConnector
#define _SkyLoginConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_delthas_skype_SkyLoginConnector
 * Method:    getUIC
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_delthas_skype_SkyLoginConnector_getUIC
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
